newsportal/newsportal/urls.py
from django.contrib import admin
from django.urls import path, include

from post import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('pages/', include('django.contrib.flatpages.urls')),
    path('', include('post.urls')),
    path('accounts/', include('allauth.urls')),
    path('search/', views.PostSearch.as_view(), name='post_search'),
    path('cabinet/', views.subscriptions, name='cabinet'),

]

newsportal/post/urls.py
from django.urls import path
from .views import (
    PostDetail, NewsList, ArticleList, NotificationList, PostCreate, PostHome, PostEdit, PostDelete, subscriptions
)


urlpatterns = [
    path('', PostHome.as_view(), name='portal_home'),

    path('post/<int:pk>/', PostDetail.as_view(), name='post_detail'),
    path('post/<int:pk>/delete/', PostDelete.as_view(), name='post_delete'),
    path('post/<int:pk>/edit/', PostEdit.as_view(), name='post_edit'),

    path('create/', PostCreate.as_view(), name='post_create'),

    path('news/', NewsList.as_view(), name='news_list'),

    path('article/', ArticleList.as_view(), name='article_list'),

    path('notification/', NotificationList.as_view(), name='notification_list'),

    path('subscriptions/', subscriptions, name='subscriptions'),

]

newsportal/post/models.py
from django.db import models
from django.utils import timezone
from django.contrib.auth.models import User
from django.db.models import Sum
from django.urls import reverse


# создание модели Автора новости/статьи
class Author(models.Model):
    authorUser = models.OneToOneField(User, unique=True, on_delete=models.CASCADE)
    ratingAuthor = models.SmallIntegerField(default=0)

    # метод подсчёта рейтинга пользователя
    def update_rating(self):
        resultPost = self.post_set.aggregate(postRating=Sum('rating'))
        ratingPost = 0
        ratingPost += resultPost.get('postRating')

        resultComment = self.post_set.aggregate(commentRating=Sum('rating'))
        ratingComment = 0
        ratingComment += resultComment.get('commentRating')

        self.ratingAuthor = ratingPost*3 + ratingComment
        self.save()

    def __str__(self):
        return self.authorUser.username

    class Meta:
        verbose_name = 'Автор'
        verbose_name_plural = 'Авторы'

# создание модели Категории новости/статьи (спорт, политика, образование и т. д.)
class Category(models.Model):
    name = models.CharField(max_length=64, unique=True, verbose_name='Название категории')
    discription = models.TextField(verbose_name='Описание категории')
    subscribers = models.ManyToManyField(User, blank=True, related_name='categories', verbose_name='Подписчики', through='Subscriber')

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = 'Категория'
        verbose_name_plural = 'Категории'


# создание модели Новости/статьи, которые создают пользователи
class Post(models.Model):
    NEWS = 'NW'
    ARTICLE = 'AR'
    NOTIFICATION = 'NT'
    CATEGORY_CHOICES = (
        (NEWS, 'Новость'),
        (ARTICLE, 'Статья'),
        (NOTIFICATION, 'Объявление'),
    )
    categoryType = models.CharField(max_length=2, choices=CATEGORY_CHOICES, default=ARTICLE, verbose_name='Тип публикации')
    dateCreation = models.DateTimeField(default=timezone.now, verbose_name='Дата и время создания публикации')
    title = models.CharField(max_length=128, verbose_name='Заголовок публикации')
    text = models.TextField(verbose_name='Текст публикации')
    rating = models.SmallIntegerField(default=0, verbose_name='Рейтинг публикации')
    author = models.ForeignKey(Author, on_delete=models.CASCADE, verbose_name='Автор публикации')
    category = models.ManyToManyField(Category, verbose_name='Категория публикации')

    # метод лайков
    def like(self):
        self.rating += 1
        self.save()

    # метод дизлайков
    def dislike(self):
        self.rating -= 1
        self.save()

    def preview(self):
        return f'{self.text[0:29]} ...'

    def get_absolute_url(self):
        return reverse('post_detail', args=[str(self.id)])

    class Meta:
        ordering = ['-dateCreation',]
        verbose_name = 'Публикация'
        verbose_name_plural = 'Публикации'

    def __str__(self):
        return self.title


# создание модели Комментарии
class Comment(models.Model):
    text = models.TextField()
    dateCreation = models.DateTimeField(auto_now_add=True)
    rating = models.SmallIntegerField(default=0)
    commentPost = models.ForeignKey(Post, on_delete=models.CASCADE)
    commentUser = models.ForeignKey(User, on_delete=models.CASCADE)

    # метод лайков
    def like(self):
        self.rating += 1
        self.save()

    # метод дизлайков
    def dislike(self):
        self.rating -= 1
        self.save()

    class Meta:
        verbose_name = 'Комментарий'
        verbose_name_plural = 'Комментарии'


class Subscriber(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE, related_name='subscriptions',)
    category = models.ForeignKey(Category, on_delete=models.CASCADE, related_name='subscriptions',)

newsportal/post/forms.py
from django import forms
from django.core.exceptions import ValidationError

from .models import Post

class PostForm(forms.ModelForm):
   class Meta:
       model = Post
       fields = [
           'author',
           'categoryType',
           'category',
           'title',
           'text',

       ]

   def clean(self):
       cleaned_data = super().clean()
       title = cleaned_data.get("title")
       text = cleaned_data.get("text")
       if title is not None and len(title) < 3 or text is not None and len(text) < 3:
           raise ValidationError({
               "title": "Заголовок не может быть менее 3 символов.",
               "text": "Текст не может быть менее 3 символов."
           })

       if text == title:
           raise ValidationError(
               "Текст не должен быть идентичным заголовоку."
           )

       return cleaned_data


# class SearchForm(forms.ModelForm):
#     class Meta:
#         model = Post
#         fields = [
#             'title',
#             'category',
#             #'dateCreation',
#         ]

class EditForm(forms.ModelForm):
    class Meta:
        model = Post
        fields = ['category', 'title', 'text']

newsportal/post/views.py
from django.shortcuts import redirect, render
from django.contrib.auth.mixins import PermissionRequiredMixin # , LoginRequiredMixin
# from django.urls import reverse_lazy
from django.views.generic import (DetailView, ListView, CreateView, UpdateView, DeleteView)
from django.contrib.auth.decorators import login_required
from django.db.models import Exists, OuterRef
from django.views.decorators.csrf import csrf_protect
# from django.conf import settings

from .models import Post, Category, Subscriber
from .filters import PostFilter
from .forms import PostForm, EditForm


class PostDetail(DetailView):
    # Модель по которой мы хотим получать информацию по отдельной статье
    model = Post
    # Используем шаблон — post_detail.html
    template_name = "post/post_detail.html"
    # Название объекта, в котором будет выбранная пользователем статья
    context_object_name = "postdetail"


class PostList(ListView):
    model = Post
    ordering = '-dateCreation'
    template_name = 'flatpages/home.html'
    context_object_name = 'postlist'    # название класса, по которому будем обращаться в коде
    paginate_by = 10    # количество записей на странице

    # Переопределяем функцию получения списка товаров
    def get_queryset(self):
        # Получаем обычный запрос
        queryset = super().get_queryset()
        # Используем наш класс фильтрации.
        # self.request.GET содержит объект QueryDict, который мы рассматривали
        # в этом юните ранее.
        # Сохраняем нашу фильтрацию в объекте класса,
        # чтобы потом добавить в контекст и использовать в шаблоне.
        self.filterset = PostFilter(self.request.GET, queryset)
        # Возвращаем из функции отфильтрованный список товаров
        return self.filterset.qs

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        # Добавляем в контекст объект фильтрации.
        context['filterset'] = self.filterset
        return context


class NewsList(ListView):
    model = Post
    ordering = '-dateCreation'
    template_name = 'post/news_list.html'
    context_object_name = 'newslist'
    paginate_by = 10

    # Переопределяем функцию получения списка товаров
    def get_queryset(self):
        # Получаем обычный запрос
        queryset = super().get_queryset()
        # Используем наш класс фильтрации.
        # self.request.GET содержит объект QueryDict, который мы рассматривали
        # в этом юните ранее.
        # Сохраняем нашу фильтрацию в объекте класса,
        # чтобы потом добавить в контекст и использовать в шаблоне.
        self.filterset = PostFilter(self.request.GET, queryset)
        # Возвращаем из функции отфильтрованный список товаров
        return self.filterset.qs

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        # Добавляем в контекст объект фильтрации.
        context['filterset'] = self.filterset
        return context


class ArticleList(ListView):
    model = Post
    ordering = '-dateCreation'
    template_name = 'post/article_list.html'
    context_object_name = 'articlelist'
    paginate_by = 10


class NotificationList(ListView):
    model = Post
    ordering = '-dateCreation'
    template_name = 'post/notification_list.html'
    context_object_name = 'notificationlist'
    paginate_by = 10


class PostCreate(PermissionRequiredMixin, CreateView):
    # запрос на наличие указанных нами прав
    permission_required = ('post.add_post',)
    # raise_exception = True    # аутентификация
    # Указываем нашу разработанную форму
    form_class = PostForm
    model = Post
    # и новый шаблон, в котором используется форма.
    template_name = 'post/post_create.html'


class PostSearch(ListView):
    model = Post
    template_name = 'flatpages/search.html'
    context_object_name = 'search'
    filterset_class = PostFilter
    ordering = '-dateCreation'
    paginate_by = 10

    def get_queryset(self):
        queryset = super().get_queryset()
        self.filterset = PostFilter(self.request.GET, queryset)
        return self.filterset.qs

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['filterset'] = self.filterset
        return context


class PostHome(ListView):
    model = Post
    ordering = '-dateCreation'
    template_name = 'flatpages/home.html'
    context_object_name = 'postlist'
    paginate_by = 10

    # Переопределяем функцию получения списка товаров
    def get_queryset(self):
        # Получаем обычный запрос
        queryset = super().get_queryset()
        # Используем наш класс фильтрации.
        # self.request.GET содержит объект QueryDict, который мы рассматривали
        # в этом юните ранее.
        # Сохраняем нашу фильтрацию в объекте класса,
        # чтобы потом добавить в контекст и использовать в шаблоне.
        self.filterset = PostFilter(self.request.GET, queryset)
        # Возвращаем из функции отфильтрованный список товаров
        return self.filterset.qs

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        # Добавляем в контекст объект фильтрации.
        context['filterset'] = self.filterset
        return context


class PostEdit(PermissionRequiredMixin, UpdateView):
    permission_required = ('post.change_post',)
    # raise_exception = True
    form_class = EditForm
    model = Post
    template_name = 'post/post_edit.html'

    def form_valid(self, form):
        return super().form_valid(form)


class PostDelete(PermissionRequiredMixin, DeleteView):
    permission_required = ('post.delete_post',)
    # raise_exception = True
    model = Post
    template_name = 'post/post_delete.html'
    context_object_name = 'postdelete'

    def form_valid(self, form):
        self.object.delete()
        return redirect('portal_home')


@login_required
@csrf_protect
def subscriptions(request):
    if request.method == 'POST':
        # user = request.user
        category_id = request.POST.get('category_id')
        category = Category.objects.get(id=category_id)
        action = request.POST.get('action')

        if action == 'subscribe':
            Subscriber.objects.create(user=request.user, category=category)
        elif action == 'unsubscribe':
            Subscriber.objects.filter(
                user=request.user,
                category=category,
            ).delete()

    categories_with_subscriptions = Category.objects.annotate(
        user_subscribed=Exists(
            Subscriber.objects.filter(
                user=request.user,
                category=OuterRef('pk'),
            )
        )
    ).order_by('name')
    return render(
        request,
        'post/subscriptions.html',
        # 'account/personal_cabinet.html',
        {'categories': categories_with_subscriptions},
    )

newsportal/templates/post/article_list.html
{% extends "flatpages/default.html" %}
{% load censor %}
{% load custom_tags %}


{% block content %}

    {% for post in articlelist %}
        {% if post.categoryType == 'AR' %}
        <article class="media content-section">
          <div class="media-body">
            <div class="article-metadata">
                <a class="text-muted"> {{ post.get_categoryType_display }} автора: </a>
                <a class="mr-2" href="#"> {{ post.author }}, </a>
                <a class="text-muted">дата публикации: {{ post.dateCreation|date:"d.m.Y" }}</a>
            </div>
              <h4><a class="article-title" href="{{ post.get_absolute_url }}">{{ post.title|censor_w }}</a></h4>
              <p class="article-content">{{ post.text|truncatechars:21|censor_w }}</p>

          </div>
        </article>
        {% endif %}
    {% endfor %}

{# Добавляем пагинацию на страницу #}

   {# Информация о предыдущих страницах #}
   {% if page_obj.has_previous %}
       <a href="?{% url_replace page=1 %}">1</a>
       {% if page_obj.previous_page_number != 1 %}
           ...
           <a href="?{% url_replace page=page_obj.previous_page_number %}">{{ page_obj.previous_page_number }}</a>
       {% endif %}
   {% endif %}

   {# Информация о текущей странице #}
   {{ page_obj.number }}

   {# Информация о следующих страницах #}
   {% if page_obj.has_next %}
       <a href="?{% url_replace page=page_obj.next_page_number %}">{{ page_obj.next_page_number }}</a>
       {% if paginator.num_pages != page_obj.next_page_number %}
           ...
           <a href="?{% url_replace page=page_obj.paginator.num_pages %}">{{ page_obj.paginator.num_pages }}</a>
       {% endif %}
   {% endif %}

{% endblock content %}

newsportal/templates/post/news_list.html
{% extends "flatpages/default.html" %}
{% load censor %}
{% load custom_tags %}


{% block content %}

    {% for post in newslist %}
        {% if post.categoryType == 'NW' %}
        <article class="media content-section">
          <div class="media-body">
            <div class="article-metadata">
                <a class="text-muted"> {{ post.get_categoryType_display }} автора: </a>
                <a class="mr-2" href="#"> {{ post.author }}, </a>
                <a class="text-muted">дата публикации: {{ post.dateCreation|date:"d.m.Y" }}</a>
            </div>
              <h4><a class="article-title" href="{{ post.get_absolute_url }}">{{ post.title|censor_w }}</a></h4>
              <p class="article-content">{{ post.text|truncatechars:21|censor_w }}</p>

          </div>
        </article>
        {% endif %}
    {% endfor %}

{# Добавляем пагинацию на страницу #}

   {# Информация о предыдущих страницах #}
   {% if page_obj.has_previous %}
       <a href="?{% url_replace page=1 %}">1</a>
       {% if page_obj.previous_page_number != 1 %}
           ...
           <a href="?{% url_replace page=page_obj.previous_page_number %}">{{ page_obj.previous_page_number }}</a>
       {% endif %}
   {% endif %}

   {# Информация о текущей странице #}
   {{ page_obj.number }}

   {# Информация о следующих страницах #}
   {% if page_obj.has_next %}
       <a href="?{% url_replace page=page_obj.next_page_number %}">{{ page_obj.next_page_number }}</a>
       {% if paginator.num_pages != page_obj.next_page_number %}
           ...
           <a href="?{% url_replace page=page_obj.paginator.num_pages %}">{{ page_obj.paginator.num_pages }}</a>
       {% endif %}
   {% endif %}

{% endblock content %}

newsportal/templates/post/notification_list.html
{% extends "flatpages/default.html" %}
{% load censor %}
{% load custom_tags %}


{% block content %}

    {% for post in notificationlist %}
        {% if post.categoryType == 'NT' %}
        <article class="media content-section">
          <div class="media-body">
            <div class="article-metadata">
                <a class="text-muted"> {{ post.get_categoryType_display }} автора: </a>
                <a class="mr-2" href="#"> {{ post.author }}, </a>
                <a class="text-muted">дата публикации: {{ post.dateCreation|date:"d.m.Y" }}</a>
            </div>
              <h4><a class="article-title" href="{{ post.get_absolute_url }}">{{ post.title|censor_w }}</a></h4>
              <p class="article-content">{{ post.text|truncatechars:21|censor_w }}</p>

          </div>
        </article>
        {% endif %}
    {% endfor %}

{# Добавляем пагинацию на страницу #}

   {# Информация о предыдущих страницах #}
   {% if page_obj.has_previous %}
       <a href="?{% url_replace page=1 %}">1</a>
       {% if page_obj.previous_page_number != 1 %}
           ...
           <a href="?{% url_replace page=page_obj.previous_page_number %}">{{ page_obj.previous_page_number }}</a>
       {% endif %}
   {% endif %}

   {# Информация о текущей странице #}
   {{ page_obj.number }}

   {# Информация о следующих страницах #}
   {% if page_obj.has_next %}
       <a href="?{% url_replace page=page_obj.next_page_number %}">{{ page_obj.next_page_number }}</a>
       {% if paginator.num_pages != page_obj.next_page_number %}
           ...
           <a href="?{% url_replace page=page_obj.paginator.num_pages %}">{{ page_obj.paginator.num_pages }}</a>
       {% endif %}
   {% endif %}

{% endblock content %}

newsportal/templates/post/post_create.html
<!--  наследуемся от шаблона default.html, который мы создавали -->
{% extends 'flatpages/default.html' %}

{% block content %}
<h1>Публикация новости/статьи/объявления:</h1>
<hr>
<form action="" method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="Сохранить" />
</form>
{% endblock content %}

newsportal/templates/post/post_delete.html
{% extends 'flatpages/default.html' %}
{% load censor %}

{% block content %}
 <h4>{{ postdelete.title }}</h4>
 <a>{{ postdelete.text }}</a>
 <hr>
 <a>{{ postdelete.get_categoryType_display }} автора: {{ postdelete.author }},</a>
 <a>дата публикации: {{ postdelete.dateCreation|date:"d.m.Y" }}</a>
 <hr>

  <p>Вы уверены, что хотите удалить эту публикацию?</p>
  <form method="post">
    {% csrf_token %}
    <button type="submit">Удалить</button>
  </form>
{% endblock %}

newsportal/templates/post/post_detail.html
<!--  наследуемся от шаблона default.html, который мы создавали -->
{% extends 'flatpages/default.html' %}

{% load censor %}

<!-- Название у нас будет News -->
{% block title %}
Post
{% endblock title %}

<!-- В контенте на странице мы выводим саму новость, идентификатор которой был передан в url -->
{% block content %}
<h2>{{ postdetail }}</h2>
    <article class="media content-section">
          <div class="media-body">
            <div class="article-metadata">
                <a class="text-muted"> {{ postdetail.get_categoryType_display }} автора: </a>
                <a class="mr-2" href="#"> {{ postdetail.author }}, </a>
                <a class="text-muted">дата публикации: {{ postdetail.dateCreation|date:"d.m.Y" }}</a>
            </div>
            <p class="article-content">{{ postdetail.text|censor_w }}</p>
          </div>
    </article>
{% if perms.post.change_post%}
<a class="mr-2" href="{% url 'post_edit' pk=postdetail.id %}"> Редактировать </a>
{% endif %}
{% if perms.post.delete_post%}
<a class="mr-2" href="{% url 'post_delete' pk=postdetail.id %}"> Удалить </a>
{% endif %}

{% endblock content %}

newsportal/templates/post/post_edit.html
{% extends 'flatpages/default.html' %}

{% block content %}
<h2>Редактирование новости/статьи/объявления:</h2>
<hr>
<form action="" method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="Обновить" />
</form>
{% endblock content %}

newsportal/templates/post/subscriptions.html
{% extends 'flatpages/default.html' %}

{% block title %}
Подписки
{% endblock title %}

{% block content %}
    <h2>Подписки</h2>
    {% for category in categories  %}
        <p>
            {{ category.name }}
            <form method="post">
                {% csrf_token %}
                <input type="hidden" name="category_id" value="{{ category.id }}" />

                {% if category.user_subscribed %}
                    <button disabled>Подписаться</button>
                    <button name="action" value="unsubscribe">Отписаться</button>
                {% else %}
                    <button name="action" value="subscribe">Подписаться</button>
                    <button disabled>Отписаться</button>
                {% endif %}
            </form>
        </p>
    {% endfor %}
{% endblock content %}